### ISSUE TITLE
fatal error: Eigen/Core: No such file or directory

### ISSUE THREAD

**Issue by jgiemza** [halasadi/MAPS#10]
Hello,

I have trouble installing MAPS with conda. I followed the instructions from README, installed boost and eigen, but after typing make I get:

```
g++ -I/usr/local/opt/boost@1.57/include -I/usr/local/include/eigen3 -O3 -DNDEBUG -O3 -c runeems2.cpp -o runeems2.o
In file included from eems2.hpp:3:0,
                 from runeems2.cpp:2:
util.hpp:12:22: fatal error: Eigen/Core: No such file or directory
 #include <Eigen/Core>
                      ^
compilation terminated.
make: *** [runeems2.o] Error 1
```

Could you please help me in figuring out where is the problem and how to solve it ? Thanks !

**Comment by halasadi** [comment]
Hi, 

I think you need to change the path to eigen in the MAKEFILE 

i.e. this line

`EIGEN_INC = /usr/local/include/eigen3`

**Comment by jgiemza** [comment]
Thanks !
