### ISSUE TITLE
Can't bind data because some arguments have the same name

### ISSUE THREAD

**Issue by j-meek** [halasadi/MAPS#13]
I am getting this error when trying to run the simulation. The code was copied directly from instruction #12 under the "Quick Start" in the README.

> plot_maps(add.pts = TRUE, add.graph = TRUE, add.countries = FALSE, longlat = TRUE, mcmcpath = "6_Inf/6_Inf-MAPS-test-sim", outpath = "6_Inf", width = 10, height = 6, plot.difference=TRUE)

plotting migration surface
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
-0.48674 -0.31423 -0.20796 -0.19944 -0.09020  0.09496 

plotting population-size surface
      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
-0.0022996  0.0007635  0.0018159  0.0018385  0.0028830  0.0057196 

plotting diagonostics of model fit and MCMC convergence
Saving 7 x 7 in image
Error: Can't bind data because some arguments have the same name
Call `rlang::last_error()` to see a backtrace

**Comment by halasadi** [comment]
You are right, thanks for reporting it. I fixed the bug. Try it now.

**Comment by halasadi** [comment]
Note: this bug was in the plotmaps package, you'll need to re-download and install the package. 

https://github.com/halasadi/plotmaps

**Comment by j-meek** [comment]
Success! Thanks so much.
