### ISSUE TITLE
plotting results

### ISSUE THREAD

**Issue by jh041** [halasadi/MAPS#16]
Hi,

The demographic changes I am seeing between time periods are subtle. I need to rescale the M and Ne gradients to better show the differences, but I'm having a hard time with the functions in plotmaps. When I put set.range=TRUE, and set new m.limits and N.limits, nothing changes from the original plotting. Playing with the "trans" option hasn't given me what I want either.

Also, like in your paper, the scale of the Ne plot is different between time periods. I would really like to be able to have the same scale in both plots, do you have any ideas how to do this?

Can you give me an example of how to use the set.range option?

What if I want to change the colors of the plot, how would you recommend I do that? 

I've tried looking at the documentation for the eems plotting scripts but nothing seems helpful. 

Thanks,

John

**Comment by halasadi** [comment]
Hi John,

(1) Can you write down the command you are using to plot the results (with the limits specified)? 

(2) Changing the colors requires changing the R code, specifically line,

```
eems.colors <- scale_fill_gradientn(colours=default_eems_colors(), 
                                      trans = "log10")
```

You would need to change default_eems_colors() to get_custom_colors() where this function is defined to suit your color taste. The function default_eems_colors() just returns a vector with colors,


```
default_eems_colors <- function( ) {
  eems.colors <- c("#994000", "#CC5800", "#FF8F33", "#FFAD66", "#FFCA99", "#FFE6CC", ## orange sequence
                   "#FBFBFB", ## very slightly off-white
                   "#CCFDFF", "#99F8FF", "#66F0FF", "#33E4FF", "#00AACC", "#007A99") ## blue sequence
  return (eems.colors)
}
```

So you can add your get_custom_colors function such as
```
get_custom_colors <- function(){
custom_colors <- c("")
return(custom_colors)
}
```
and fill in ```custom_colors``` accordingly.

**Comment by jh041** [comment]
Thanks for the quick reply,

I might be able to improve the presentation of the plot by altering the color scheme alone, so thanks for that, but here is the code that I thought would rescale the data, but doesn't.

**> plot_maps(add.pts = TRUE, add.graph = FALSE, add.countries = TRUE,
+      longlat = TRUE, mcmcpath = "./", plot.mean=T,
+      outpath = "./", width = 10, height = 6, set.range=TRUE, m.limits=c(10000,1000), N.limits=c(10,0.1))**

Anything I should be doing differently?

**Comment by jh041** [comment]
Thanks for your quick reply.

I might be able to improve the visuals of the plot with colors alone, but here is the command that I am using that I thought should rescale the data, but doesn't.

**plot_maps(add.pts = TRUE, add.graph = FALSE, add.countries = TRUE,
longlat = TRUE, mcmcpath = "./", plot.mean=T,
outpath = "./", width = 10, height = 6, set.range=TRUE, m.limits=c(10000,1000), N.limits=c(10,0.1))**

Is there something I am missing here?

**Comment by halasadi** [comment]
The plot_maps command seems off,

both your limits should start with the lower bound and end with the upper bound, for example

m.limits = c(0.001, 0.1)
N.limits  = c(1, 1e6)

Also your migration rates seem high (e.g. 10000) and your population sizes low (0.1). Is that what you expect for the species you are studying?

**Comment by jh041** [comment]
Ah... that was it. the lower bound needs to come first in the order. I'll never make that mistake again.

Yes, the migration rates are high and the population sizes are low. I'm working on a near-threatened marine fish.
